### PR TITLE
feat: add capacitor 3 support

### LINKED ISSUE #8: Capacitor 3 Support
Updating Capacitor to 3.0.  
Guide: https://capacitorjs.com/docs/v3/updating/plugins/3-0  
New plugin template: https://github.com/ionic-team/create-capacitor-plugin/tree/main/assets/plugin-template

### PR DESCRIPTION
**Pull request by robingenz**
Close #8

### CODE REVIEW

**Comment by alfredosalzillo** [comment]
news on this?

**Comment by robingenz** [comment]
I will try to work on this PR over the weekend. Unfortunately, other projects have a higher priority right now.

**Comment by webzlodimir** [comment]
We are looking forward to this update, thank you!

**Comment by robingenz** [comment]
Released with version `1.0.0-alpha.3` ([npm](https://www.npmjs.com/package/@robingenz/capacitor-app-update/v/1.0.0-alpha.3)).

**Pull request merged**
